### ISSUE TITLE
Version out of date in bower.json

### ISSUE THREAD

**Issue by rek** [simonblee/marionette-dust#8]
Errors when installing with bower:

    bower marionette-dust#0.3.1         extract archive.tar.gz
    bower marionette-dust#0.3.1         mismatch Version declared in the json (0.1.6) is different than the resolved one (0.3.1)
    bower marionette-dust#0.3.1         invalid-meta backbone.marionette.dust is missing "ignore" entry in bower.json

**Comment by simonblee** [comment]
aa9d93918782864f80b032336103efd419b0dd1b
